### ISSUE TITLE
HELP!: lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1 error

### ISSUE THREAD

**Issue by olivier22r** [pkaczynski/xml2xlsx#1]
Hi, 

i am trying to use your script to convert a standard XML file to XLSX file. I am new to python and i am getting the error lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1.

With a simple script such as

```
from xml2xlsx import xml2xlsx

def ConvertXmlToXlsx(self):
    xml2xlsx("C:\Python27\PythonExcel\\test.xml")
```

I am not sure how to input my xml file in your function.

thanks

Olivier

**Comment by pkaczynski** [comment]
Hi,
Thank you for your question. First one :)

You should open the file, read it, and pass string to the function (not the path to the file). Than you can save the result to another file (xlsx).

Sorry for slacky documentation. I will update it soon, along with some other improvements.

Should you have any other questions or comments, don't hesitate to open another issue.

**Comment by pkaczynski** [comment]
I've added Python 3 support and updated documenation a little bit. Cheers!
